import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';
const modulePath=process.env.BTG_PLAYWRIGHT_MODULE||'playwright';const {chromium}=await import(modulePath);
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];
const base=process.env.BTG_TEST_URL||'http://127.0.0.1:8000/browsertonegen/';
const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};const state=()=>page.evaluate(()=>globalThis.btg.config);const diag=()=>page.evaluate(()=>globalThis.btg.diagnostics);
try{
await page.goto(base);await page.waitForSelector('[data-tone]');
await check('load subpath; eight tones; silent until gesture',async()=>{assert.equal(await page.locator('[data-tone]').count(),8);assert.equal((await diag()).contextState,'not created');assert.ok(await page.title().then(t=>t.includes('BrowserToneGen')));});
await check('simple advanced mode preserves settings',async()=>{const s=await state();await page.locator('#advanced').check();await page.locator('#advanced').uncheck();assert.deepEqual(await state(),s);});
await check('add duplicate reorder remove tone',async()=>{await page.locator('#addTone').click();assert.equal((await state()).tones.length,9);await page.getByRole('button',{name:'Duplicate tone 1',exact:true}).click();assert.equal((await state()).tones.length,10);const id=(await state()).tones[0].id;await page.getByRole('button',{name:'Move tone 1 down',exact:true}).click();assert.equal((await state()).tones[1].id,id);await page.getByRole('button',{name:'Remove tone 1',exact:true}).click();assert.equal((await state()).tones.length,9);});
await check('preset load; real AudioWorklet start; measured output',async()=>{await page.locator('#builtinPreset').selectOption('1 kHz reference');await page.locator('#loadBuiltin').click();assert.equal((await state()).tones[0].frequency,1000);await page.locator('#start').click();await page.waitForFunction(()=>globalThis.btg.diagnostics.state==='running');await page.waitForFunction(()=>globalThis.btg.diagnostics.lastLevels?.rmsL>0);assert.ok((await diag()).lastLevels.rmsL>0);assert.equal((await diag()).nodeCount,5);});
await check('live frequency phase routing gain and mute wired',async()=>{const row=page.locator('[data-tone]').first();await row.locator('[data-field=frequency]').fill('880');await row.locator('[data-field=frequency]').press('Tab');assert.equal((await state()).tones[0].frequency,880);await page.locator('#advanced').check();await row.getByText('Routing, timing & precision',{exact:true}).click();await row.locator('[data-field=route]').selectOption('left');await row.locator('[data-field=phase]').fill('90');await row.locator('[data-field=phase]').press('Tab');await page.waitForFunction(()=>globalThis.btg.diagnostics.lastLevels?.rmsR===0);assert.equal((await state()).tones[0].phase,90);await page.locator('#masterMute').check();await page.waitForFunction(()=>globalThis.btg.diagnostics.lastLevels?.rmsL===0);await page.locator('#masterMute').uncheck();});
await check('pause freezes context; resume; panic disconnects',async()=>{await page.locator('#pause').click();await page.waitForFunction(()=>globalThis.btg.diagnostics.state==='paused');assert.equal((await diag()).contextState,'suspended');await page.locator('#pause').click();await page.waitForFunction(()=>globalThis.btg.diagnostics.state==='running');await page.locator('#panic').click();assert.equal((await diag()).state,'stopped');assert.equal((await diag()).nodeCount,0);});
await check('saved preset CRUD persistence; JSON downloads',async()=>{await page.locator('#presetName').fill('Browser test ♯');await page.locator('#savePreset').click();assert.equal(await page.locator('#savedPreset').inputValue(),'Browser test ♯');await page.locator('#duplicatePreset').click();assert.match(await page.locator('#savedPreset').inputValue(),/copy/);await page.locator('#presetName').fill('Renamed');await page.locator('#renamePreset').click();assert.equal(await page.locator('#savedPreset').inputValue(),'Renamed');await page.locator('#loadPreset').click();const download=page.waitForEvent('download');await page.locator('#exportJson').click();const file=await download;const text=await readFile(await file.path(),'utf8');assert.equal(JSON.parse(text).schemaVersion,1);await page.locator('#deletePreset').click();await page.reload();assert.ok((await page.locator('#savedPreset').allTextContents()).join('').includes('Browser test ♯'));});
await check('invalid JSON import leaves last valid state; valid import silent',async()=>{const before=await state();await page.locator('#importJson').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{')});await page.waitForSelector('#error:not([hidden])');assert.deepEqual(await state(),before);await page.locator('#importJson').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(before))});await page.waitForFunction(()=>document.getElementById('status').textContent.includes('valid.json'));assert.equal((await diag()).state,'stopped');});
await check('sweep controls, additive pattern and modulation wiring',async()=>{await page.locator('#advanced').check();const row=page.locator('[data-tone]').first();await row.locator('[data-field=kind]').selectOption('sweep');await row.locator('[data-field=endFrequency]').fill('1000');await row.locator('[data-field=endFrequency]').press('Tab');await row.locator('[data-field=spacing]').selectOption('linear');assert.equal((await state()).tones[0].endFrequency,1000);await row.getByText('Additive harmonic editor',{exact:true}).click();await row.locator('[data-pattern]').selectOption('odd');await row.getByRole('button',{name:'Apply pattern & use additive'}).click();assert.equal((await state()).tones[0].wave,'additive');assert.equal((await state()).tones[0].harmonics[1],0);await row.getByText('Modulation',{exact:true}).click();await row.locator('[data-field=mod]').selectOption('fm');assert.equal((await state()).tones[0].modDepth,20);});
await check('sequence stage CRUD and shared sequence settings',async()=>{await page.locator('#addStage').click();assert.equal((await state()).sequence.length,4);await page.locator('[data-stage="3"] [data-field=type]').selectOption('pink');assert.equal((await state()).sequence[3].type,'pink');await page.getByRole('button',{name:'Move stage 4 up',exact:true}).click();assert.equal((await state()).sequence[2].type,'pink');await page.getByRole('button',{name:'Remove stage 4',exact:true}).click();assert.equal((await state()).sequence.length,3);await page.locator('#sequenceLoop').check();assert.equal((await state()).sequenceLoop,true);});
await check('timer automatically stops and Escape panic',async()=>{await page.locator('#builtinPreset').selectOption('440 Hz');await page.locator('#loadBuiltin').click();await page.locator('#timerDuration').fill('.1');await page.locator('#timerDuration').press('Tab');await page.locator('#start').click();await page.waitForFunction(()=>globalThis.btg.diagnostics.state==='stopped');await page.locator('#timerDuration').fill('0');await page.locator('#timerDuration').press('Tab');await page.locator('#start').click();await page.waitForFunction(()=>globalThis.btg.diagnostics.state==='running');await page.keyboard.press('Escape');assert.equal((await diag()).state,'stopped');});
await check('WAV worker download: 24-bit 44.1k mono normalization',async()=>{await page.locator('#exportDuration').fill('.1');await page.locator('#exportRate').selectOption('44100');await page.locator('#exportDepth').selectOption('24');await page.locator('#exportChannels').selectOption('1');await page.locator('#normalize').check();const promise=page.waitForEvent('download');await page.locator('#exportWav').click();const download=await promise,buf=await readFile(await download.path());assert.equal(buf.toString('ascii',0,4),'RIFF');assert.equal(buf.readUInt16LE(22),1);assert.equal(buf.readUInt32LE(24),44100);assert.equal(buf.readUInt16LE(34),24);assert.equal(buf.length,44+4410*3);});
await check('musical calculator and add calculated tone',async()=>{await page.locator('#calcNote').selectOption('9');await page.locator('#calcOctave').fill('4');await page.locator('#calcA4').fill('432');await page.locator('#noteConvert').click();assert.equal(Number(await page.locator('#calcFreq').inputValue()),432);await page.locator('#addCalcTone').click();assert.equal((await state()).tones.at(-1).frequency,432);});
await check('URL restore no autoplay and both navigation links',async()=>{await page.locator('#share').click();const url=await page.locator('#shareUrl').inputValue();assert.ok(url.includes('#config='));await page.goto(url);await page.waitForSelector('[data-tone]');assert.equal((await diag()).contextState,'not created');assert.ok(await page.locator('a[href="https://djshellshoxxx.github.io/circuitdriftlabs/"]').count()>=2);});
await check('display toggle, Help/About and 390px responsive layout',async()=>{await page.locator('#visuals').uncheck();assert.equal(await page.locator('#scope').isVisible(),false);await page.locator('#visuals').check();await page.locator('#helpButton').click();assert.equal(await page.locator('#help').isVisible(),true);await page.locator('#help [data-close]').click();await page.locator('#aboutButton').click();await page.locator('#about [data-close]').click();await page.setViewportSize({width:390,height:844});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false);await page.locator('#advanced').check();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);});
assert.deepEqual(errors,[]);console.log(`Browser checks: ${results.length} passed. Browser: ${browser.version()}`);await writeFile('docs/BROWSER_RESULTS.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),base,checks:results,errors},null,2));
}finally{await browser.close();}
