import {VERSION,MAX_TONES,AUTOMATABLE,bounds,WAVES,NOTE_NAMES,defaults,tone,validate,parsePreset,serialize,dbToAmp,ampToDb,noteLabel,noteToFreq,number,cents,harmonicPattern,group,PRESETS,builtin,encodeState,decodeState} from './model.js';
import {Engine} from './engine.js';
const $=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=defaults(),saved={},worker=null,stats={},logs=[],visualTick=0,starting=false,recorder=null,recordStream=null,recordGain=null,recordTimer=null;
const engine=new Engine(s=>{stats=s;if(s.done){finishRecording();renderTransport();message('Timer completed.');}},error);
const rate=()=>engine.context?.sampleRate||48000;
function log(type,data){if($('debug').checked){logs.push({time:new Date().toISOString(),type,data});if(logs.length>300)logs.shift();}}
function error(e){$('error').hidden=false;$('error').textContent=e.message||String(e);log('error',$('error').textContent);renderTransport();}
function message(s){$('error').hidden=true;$('status').textContent=s;log('event',s);}
function commit(next,refresh=true){try{const valid=validate(next,rate());engine.update(valid);state=valid;if(refresh)render();else summary();return true;}catch(e){error(e);return false;}}
const select=(key,value,choices)=>`<label>${escape(key.label||key)}<select data-field="${key.name||key}">${choices.map(x=>{const [v,label]=Array.isArray(x)?x:[x,x];return `<option value="${escape(v)}" ${v===value?'selected':''}>${escape(label)}</option>`;}).join('')}</select></label>`;
const field=(name,label,value,min,max,step='.01',extra='')=>`<label>${escape(label)}<input data-field="${name}" type="number" value="${value}" min="${min}" max="${max}" step="${step}" ${extra}></label>`;
const check=(name,label,value)=>`<label class="check"><input type="checkbox" data-field="${name}" ${value?'checked':''}>${label}</label>`;
function renderTones(){const open=new Set([...document.querySelectorAll('#tones details[open]')].map(d=>d.dataset.key));const focus=document.activeElement,identity=focus?.closest('[data-tone]')?.dataset.tone,f=focus?.dataset.field;
$('tones').innerHTML=state.tones.map((v,i)=>`<article class="tone ${v.enabled?'':'disabled'}" data-tone="${escape(v.id)}"><div class="tone-top"><strong>T${String(i+1).padStart(2,'0')}</strong>${check('enabled','Enabled',v.enabled)}${check('muted','Mute',v.muted)}${check('solo','Solo',v.solo)}<div class="actions"><button data-action="up" aria-label="Move tone ${i+1} up" ${i===0?'disabled':''}>↑</button><button data-action="down" aria-label="Move tone ${i+1} down" ${i===state.tones.length-1?'disabled':''}>↓</button><button data-action="duplicate" aria-label="Duplicate tone ${i+1}">Duplicate</button><button data-action="remove" aria-label="Remove tone ${i+1}">Remove</button></div></div>
<div class="tone-main"><div class="frequency-field"><label>Frequency Hz<input data-field="frequency" type="number" min=".1" max="${rate()/2-1}" step=".01" value="${v.frequency}"></label><input aria-label="Tone ${i+1} logarithmic frequency" data-field="coarse" type="range" min="-1" max="${Math.log10(rate()/2-1)}" step=".001" value="${Math.log10(v.frequency)}"><div class="freq-tools"><button data-action="minus" aria-label="Decrease tone ${i+1} by 0.1 Hz">−</button><output>${(v.frequency/1000).toFixed(4)} kHz · ${escape(noteLabel(v.frequency,Number($('calcA4').value)||440))}</output><button data-action="plus" aria-label="Increase tone ${i+1} by 0.1 Hz">+</button></div></div>${select({name:'wave',label:'Waveform'},v.wave,WAVES)}${field('amplitude','Amplitude',v.amplitude,0,1,'.001')}</div>
<div class="fields">${select({name:'kind',label:'Signal mode'},v.kind,[['tone','Continuous tone'],['sweep','Sweep'],['steps','Stepped sequence'],['sequence','Sequence editor']])}<span class="hint">${v.kind==='tone'?'Independent signal':v.kind==='sequence'?'Uses shared sequence editor':'Starts at tone frequency'}</span></div>
${v.kind==='sweep'||v.kind==='steps'?`<div class="fields">${field('endFrequency','End Hz',v.endFrequency,.1,rate()/2-1)}${select({name:'spacing',label:'Spacing'},v.spacing,['linear','log'])}${select({name:'direction',label:'Direction'},v.direction,['forward','reverse','pingpong'])}${v.kind==='sweep'?field('sweepDuration','Seconds per sweep leg',v.sweepDuration,.01,3600):field('steps','Number of steps',v.steps,2,128,'1')+field('dwell','Seconds per step',v.dwell,.001,60,'.001')+field('transition','Transition fraction',v.transition,0,1)}${field('repeats','Repetitions',v.repeats,1,100,'1')}${check('loop','Loop signal',v.loop)}</div>`:''}
<details class="advanced" data-key="${v.id}-voice"><summary>Routing, timing & precision</summary><div class="fields">${field('db','Gain dB',ampToDb(v.amplitude).toFixed(3),-80,0,'.1')}${field('phase','Phase °',v.phase,-360,360)}${field('pan','Pan (−1 left / +1 right)',v.pan,-1,1,'.01')}${select({name:'route',label:'Channels'},v.route,['both','left','right'])}${check('invert','Invert polarity',v.invert)}${field('delay','Start delay s',v.delay,0,3600)}${field('duration','Duration s (0 continuous)',v.duration,0,3600)}${field('fadeIn','Fade in s',v.fadeIn,0,30)}${field('fadeOut','Fade out s',v.fadeOut,0,30)}${field('pulseWidth','Pulse duty 0.01–0.99',v.pulseWidth,.01,.99)}${select({name:'stereoMotion',label:'Stereo motion'},v.stereoMotion,['none','alternate','pan'])}${field('motionPeriod','Motion period s',v.motionPeriod,.01,60)}</div><label>Fine frequency ±100 cents<input data-field="fine" data-base="${v.frequency}" type="range" min="-100" max="100" step=".1" value="0"></label></details>
${renderAutomation(v)}<details class="advanced" data-key="${v.id}-mod"><summary>Modulation</summary><div class="fields">${select({name:'mod',label:'Sine LFO modulation'},v.mod,['none','am','fm','tremolo','vibrato','ring'])}${field('modFrequency','LFO Hz',v.modFrequency,.01,1000)}${field('modDepth',v.mod==='fm'?'Depth Hz':v.mod==='vibrato'?'Depth cents':'Depth / amount',v.modDepth,0,v.mod==='fm'?20000:v.mod==='vibrato'?2400:1)}</div></details>
<details class="advanced" data-key="${v.id}-add"><summary>Additive harmonic editor</summary><div class="fields">${field('harmonicCount','Harmonic count',v.harmonics.length,1,32,'1')}<label>Pattern<select data-pattern><option>all</option><option>odd</option><option>even</option><option>square</option><option>triangle</option></select></label><label>Rolloff exponent<input data-rolloff type="number" min="0" max="4" step=".1" value="1"></label></div><button data-action="pattern">Apply pattern & use additive</button><div class="harmonics">${v.harmonics.map((h,k)=>`<label>H${k+1}<input data-harmonic="${k}" type="number" min="-1" max="1" step=".01" value="${h}"></label>`).join('')}</div><p class="hint">Signed amplitudes; sum normalized. Harmonics above Nyquist omitted.</p></details></article>`).join('');
for(const d of document.querySelectorAll('#tones details'))d.open=open.has(d.dataset.key);if(identity&&f){const el=[...document.querySelectorAll('[data-tone]')].find(x=>x.dataset.tone===identity)?.querySelector(`[data-field="${f}"]`);el?.focus({preventScroll:true});}}
function renderStages(){$('stages').innerHTML=state.sequence.map((s,i)=>`<div class="stage" data-stage="${i}"><div class="section-head"><strong>Stage ${i+1}</strong><div class="actions"><button data-stage-action="up" aria-label="Move stage ${i+1} up" ${i?'':'disabled'}>↑</button><button data-stage-action="remove" aria-label="Remove stage ${i+1}">Remove</button></div></div><div class="fields">${select({name:'type',label:'Signal'},s.type,['tone','silence','sweep','white','pink','brown'])}${field('frequency','Start Hz',s.frequency,.1,rate()/2-1)}${field('endFrequency','End Hz',s.endFrequency,.1,rate()/2-1)}${field('duration','Duration s',s.duration,.001,3600,'.001')}</div></div>`).join('');}
const globalFields={masterGain:['master','gain'],masterMute:['master','muted'],mono:['master','mono'],headroom:['master','headroom'],fadeStart:['master','fadeStart'],fadeStop:['master','fadeStop'],timerDelay:['timer','delay'],timerDuration:['timer','duration'],timerRepeats:['timer','repeats'],timerRest:['timer','rest'],timerLoop:['timer','loop']};
function renderGlobals(){for(const [id,[root,key]] of Object.entries(globalFields)){const el=$(id);if(el.type==='checkbox')el.checked=state[root][key];else el.value=state[root][key];}$('sequenceRepeats').value=state.sequenceRepeats;$('sequenceLoop').checked=state.sequenceLoop;$('masterReadout').textContent=`${state.master.gain.toFixed(1)} dB`;}
function summary(){const enabled=state.tones.filter(v=>v.enabled&&!v.muted),solo=enabled.some(v=>v.solo),active=enabled.filter(v=>!solo||v.solo);$('voiceCount').textContent=`${active.length} active / ${state.tones.length} of ${MAX_TONES}`;$('frequencies').textContent=active.map(v=>`${v.frequency.toFixed(2)} Hz${v.kind!=='tone'?' '+v.kind:''} · ${v.route}${v.frequency<20||v.frequency>20000?' · outside nominal hearing range':''}`).join(' / ')||'No enabled signals';$('addTone').disabled=state.tones.length>=MAX_TONES;const estimate=state.master.headroom?1/Math.max(1,active.reduce((n,v)=>n+v.amplitude*(v.wave==='pulse'?2:1),0)):1;$('levelInfo').textContent=`Auto headroom ${state.master.headroom?'on':'off'} · ${(20*Math.log10(estimate)).toFixed(1)} dB compensation${stats.clipped?' · LIMITING':''}`;}
function renderTransport(){$('transportState').textContent=starting?'Starting…':engine.state[0].toUpperCase()+engine.state.slice(1);$('pause').textContent=engine.state==='paused'?'Resume':'Pause';$('pause').setAttribute('aria-pressed',String(engine.state==='paused'));$('pause').disabled=engine.state==='stopped';$('start').disabled=starting||engine.state==='running';$('sampleRate').textContent=engine.context?`${engine.context.sampleRate.toLocaleString()} Hz · ${engine.context.state}`:'Audio engine ready';}
function render(){renderTones();renderStages();renderGlobals();summary();renderTransport();renderMidi();}
function append(vs){if(state.tones.length+vs.length>MAX_TONES){error(Error(`Maximum ${MAX_TONES} tones. Remove unused slots first.`));return;}const next=structuredClone(state);next.tones.push(...vs);commit(next);}
$('tones').addEventListener('change',e=>{const el=e.target,row=el.closest('[data-tone]');if(!row||el.closest('[data-automation]'))return;const next=structuredClone(state),v=next.tones.find(v=>v.id===row.dataset.tone),key=el.dataset.field;try{if(el.dataset.harmonic!==undefined)v.harmonics[+el.dataset.harmonic]=Number(el.value);else if(key==='db')v.amplitude=Number(el.value)<=-80?0:dbToAmp(Number(el.value));else if(key==='coarse')v.frequency=10**Number(el.value);else if(key==='fine')v.frequency=Number(el.dataset.base)*2**(Number(el.value)/1200);else if(key==='harmonicCount'){const count=number(Number(el.value),1,32,'Harmonic count');if(!Number.isInteger(count))throw Error('Harmonic count must be an integer.');v.harmonics=Array.from({length:count},(_,i)=>v.harmonics[i]??0);}else if(key){v[key]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(key==='mod')v.modDepth=v.mod==='fm'?20:v.mod==='vibrato'?50:.25;}else return;commit(next);}catch(err){error(err);}});
$('tones').addEventListener('input',e=>{const el=e.target;if(el.dataset.field==='coarse'||el.dataset.field==='fine'){const v=state.tones.find(v=>v.id===el.closest('[data-tone]').dataset.tone),next=structuredClone(state),x=next.tones.find(t=>t.id===v.id);x.frequency=el.dataset.field==='coarse'?10**Number(el.value):Number(el.dataset.base)*2**(Number(el.value)/1200);if(commit(next,false)){const num=el.closest('[data-tone]').querySelector('[data-field=frequency]');num.value=x.frequency;el.closest('[data-tone]').querySelector('.freq-tools output').textContent=`${(x.frequency/1000).toFixed(4)} kHz · ${noteLabel(x.frequency)}`;}}});
$('tones').addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const row=button.closest('[data-tone]'),next=structuredClone(state),i=next.tones.findIndex(v=>v.id===row.dataset.tone),v=next.tones[i];switch(button.dataset.action){case 'duplicate':if(next.tones.length>=MAX_TONES){error(Error('Tone limit reached.'));return;}next.tones.splice(i+1,0,tone({...v,id:undefined}));next.tones[i+1].id=tone().id;break;case 'remove':next.tones.splice(i,1);next.midiMappings=next.midiMappings.filter(m=>m.target!==v.id);break;case 'up':[next.tones[i-1],next.tones[i]]=[v,next.tones[i-1]];break;case 'down':[next.tones[i+1],next.tones[i]]=[v,next.tones[i+1]];break;case 'minus':v.frequency=Math.max(.1,v.frequency-.1);break;case 'plus':v.frequency=Math.min(rate()/2-1,v.frequency+.1);break;case 'pattern':{const rolloff=Number(row.querySelector('[data-rolloff]').value);if(!Number.isFinite(rolloff)||rolloff<0||rolloff>4){error(Error('Rolloff must be 0–4.'));return;}v.harmonics=harmonicPattern(v.harmonics.length,row.querySelector('[data-pattern]').value,rolloff);v.wave='additive';break;}}commit(next);});
for(const [id,[root,key]] of Object.entries(globalFields))$(id).addEventListener('input',()=>{const next=structuredClone(state);next[root][key]=$(id).type==='checkbox'?$(id).checked:Number($(id).value);if(commit(next,false))$('masterReadout').textContent=`${state.master.gain.toFixed(1)} dB`;});
async function start(){if(starting)return;starting=true;renderTransport();try{await engine.start(state);if(engine.state==='running'){message('Playing.');renderTones();}}catch{}finally{starting=false;renderTransport();}}
function stop(panic=false){finishRecording();panic?engine.panic():engine.stop(state.master.fadeStop);stats={};renderTransport();message(panic?'Panic: output silenced.':'Stopped.');}
$('start').onclick=start;$('stop').onclick=()=>stop();$('panic').onclick=()=>stop(true);$('pause').onclick=async()=>{try{await engine.pause();if(recorder){if(engine.state==='paused'&&recorder.state==='recording')recorder.pause();else if(engine.state==='running'&&recorder.state==='paused')recorder.resume();}renderTransport();message(engine.state==='paused'?'Paused; audio clock frozen.':'Resumed.');}catch(e){error(e);}};
$('addTone').onclick=()=>append([tone()]);
for(const [id,key,value] of [['enableAll','enabled',true],['disableAll','enabled',false],['muteAll','muted',true],['unmuteAll','muted',false]])$(id).onclick=()=>{const next=structuredClone(state);next.tones.forEach(v=>v[key]=value);commit(next);};
$('clear').onclick=()=>{stop(true);const next=structuredClone(state);next.tones=[];next.midiMappings=[];commit(next);};$('reset').onclick=()=>{stop(true);commit(defaults());};
$('advanced').onchange=()=>{document.body.classList.toggle('advanced-mode',$('advanced').checked);};
$('builtinPreset').innerHTML=PRESETS.map(p=>`<option>${escape(p)}</option>`).join('');$('builtinPreset').value='440 Hz';
function load(s,label){stop(true);if(commit(s)){message(`Loaded ${label}. Press Start to play.`);}}
$('loadBuiltin').onclick=()=>load(builtin($('builtinPreset').value),$('builtinPreset').value);
const stereoNames=['Left only','Right only','Center','Left/right alternate','Polarity test','Phase 90°','Pan sweep','Independent L/R'];$('stereoButtons').innerHTML=stereoNames.map(n=>`<button data-stereo="${escape(n)}">${escape(n)}</button>`).join('');$('stereoButtons').onclick=e=>{if(e.target.dataset.stereo)load(builtin(e.target.dataset.stereo),e.target.dataset.stereo);};
$('addGroup').onclick=()=>{try{const mode=$('groupMode').value,f=number(Number($('groupFreq').value),.1,rate()/2-1,'Center frequency'),count=number(Number($('groupCount').value),1,32,'Group count'),spread=number(Number($('groupSpread').value),.01,20000,'Spread');if(!Number.isInteger(count))throw Error('Group count must be an integer.');const fs=group(mode,f,count,spread);fs.forEach(x=>number(x,.1,rate()/2-1,'Group frequency'));append(fs.map((x,i)=>tone({frequency:x,route:mode==='binaural'?(i?'right':'left'):'both'})));}catch(e){error(e);}};
$('stages').onchange=e=>{const row=e.target.closest('[data-stage]'),key=e.target.dataset.field;if(!row||!key)return;const next=structuredClone(state);next.sequence[+row.dataset.stage][key]=e.target.type==='number'?Number(e.target.value):e.target.value;commit(next,false);};
$('stages').onclick=e=>{const b=e.target.closest('[data-stage-action]');if(!b)return;const next=structuredClone(state),i=+b.closest('[data-stage]').dataset.stage;if(b.dataset.stageAction==='remove')next.sequence.splice(i,1);else [next.sequence[i-1],next.sequence[i]]=[next.sequence[i],next.sequence[i-1]];commit(next);};$('addStage').onclick=()=>{if(state.sequence.length>=64){error(Error('Maximum 64 stages.'));return;}const next=structuredClone(state);next.sequence.push({type:'tone',frequency:1000,endFrequency:2000,duration:2});commit(next);};
for(const id of ['sequenceRepeats','sequenceLoop'])$(id).onchange=()=>{const next=structuredClone(state);next[id]=id==='sequenceLoop'?$(id).checked:Number($(id).value);commit(next,false);};
const STORAGE='btg.presets.v1';
function readSaved(){try{const raw=localStorage.getItem(STORAGE);if(raw){const db=JSON.parse(raw);if(!db||typeof db!=='object'||Array.isArray(db)||Object.keys(db).length>100)throw Error('Invalid saved preset database.');saved={};for(const [name,config] of Object.entries(db)){if(name.length>80||['__proto__','constructor','prototype'].includes(name))throw Error('Invalid saved name.');saved[name]=validate(config,rate());}}}catch(e){saved={};error(Error(`Saved presets could not be read: ${e.message}. Import a backup JSON to recover.`));}renderSaved();}
function renderSaved(selected=''){$('savedPreset').innerHTML=Object.keys(saved).length?Object.keys(saved).map(n=>`<option value="${escape(n)}">${escape(n)}</option>`).join(''):'<option value="">No saved presets</option>';if(selected in saved)$('savedPreset').value=selected;}
function writeSaved(next,selected){try{localStorage.setItem(STORAGE,JSON.stringify(next));saved=next;renderSaved(selected);message('Local presets updated.');}catch(e){error(Error(`Presets were not saved: ${e.message}`));}}
function presetName(){const n=$('presetName').value.trim();if(!n||n.length>80||['__proto__','constructor','prototype'].includes(n))throw Error('Enter a preset name (1–80 characters).');return n;}
$('savePreset').onclick=()=>{try{const n=presetName();if(!saved[n]&&Object.keys(saved).length>=100)throw Error('Maximum 100 saved presets.');writeSaved({...saved,[n]:structuredClone(state)},n);}catch(e){error(e);}};
$('loadPreset').onclick=()=>{const n=$('savedPreset').value;if(!saved[n]){error(Error('Choose a saved preset.'));return;}load(saved[n],n);$('presetName').value=n;};
$('renamePreset').onclick=()=>{try{const old=$('savedPreset').value,n=presetName();if(!saved[old])throw Error('Choose a saved preset.');if(n!==old&&saved[n])throw Error('That name already exists.');const next={...saved,[n]:saved[old]};if(n!==old)delete next[old];writeSaved(next,n);}catch(e){error(e);}};
$('duplicatePreset').onclick=()=>{const n=$('savedPreset').value;if(!saved[n]){error(Error('Choose a saved preset.'));return;}if(Object.keys(saved).length>=100){error(Error('Maximum 100 saved presets.'));return;}let copy=n.slice(0,65)+' copy',i=2;while(saved[copy])copy=n.slice(0,65)+` copy ${i++}`;writeSaved({...saved,[copy]:structuredClone(saved[n])},copy);};$('deletePreset').onclick=()=>{const n=$('savedPreset').value;if(!saved[n])return;const next={...saved};delete next[n];writeSaved(next,'');};
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportJson').onclick=()=>download(serialize(state),'BrowserToneGen-preset.json','application/json');$('importButton').onclick=()=>$('importJson').click();$('importJson').onchange=async()=>{try{const file=$('importJson').files[0];if(!file)return;if(file.size>262144)throw Error('Preset exceeds 256 KB.');const s=parsePreset(await file.text(),rate());load(s,file.name);}catch(e){error(e);}finally{$('importJson').value='';}};
$('share').onclick=async()=>{try{const url=new URL(location.href);url.hash='config='+encodeState(state);$('shareBox').hidden=false;$('shareUrl').value=url.href;try{await navigator.clipboard.writeText(url.href);message('Share URL copied.');}catch{message('Share URL ready; select the link to copy it.');$('shareUrl').select();}}catch(e){error(e);}};
$('calcNote').innerHTML=NOTE_NAMES.map((n,i)=>`<option value="${i}">${n}</option>`).join('');$('calcNote').value='9';
function calculate(){try{const a=number(Number($('calcA4').value),300,500,'A4 reference'),f=number(Number($('calcFreq').value),.1,48000,'Frequency'),g=number(Number($('calcFreq2').value),.1,48000,'Comparison'),speed=number(Number($('calcSpeed').value),100,2000,'Speed of sound'),h=number(Number($('calcHarmonic').value),1,128,'Harmonic number');if(!Number.isInteger(h))throw Error('Harmonic number must be an integer.');$('calcResult').textContent=`${noteLabel(f,a)}\nPeriod ${(1000/f).toFixed(5)} ms · Wavelength ${(speed/f).toFixed(5)} m\nOctave ↓ ${(f/2).toFixed(3)} Hz · ↑ ${(f*2).toFixed(3)} Hz\nH${h} ${(f*h).toFixed(3)} Hz · Sub${h} ${(f/h).toFixed(3)} Hz\nRatio ${(g/f).toFixed(6)} · Difference ${cents(f,g).toFixed(3)} cents`;return f;}catch(e){error(e);return null;}}
for(const id of ['calcFreq','calcFreq2','calcA4','calcSpeed','calcHarmonic'])$(id).oninput=calculate;
$('noteConvert').onclick=()=>{try{const oct=number(Number($('calcOctave').value),-1,10,'Octave'),c=number(Number($('calcCents').value),-1200,1200,'Cents'),a=number(Number($('calcA4').value),300,500,'A4 reference');if(!Number.isInteger(oct))throw Error('Octave must be an integer.');$('calcFreq').value=noteToFreq((oct+1)*12+Number($('calcNote').value),a,c);calculate();}catch(e){error(e);}};$('addCalcTone').onclick=()=>{const f=calculate();if(f!==null)append([tone({frequency:f})]);};
function endExport(){worker?.terminate();worker=null;$('exportWav').disabled=false;$('cancelExport').disabled=true;}
$('exportWav').onclick=()=>{try{const duration=number(Number($('exportDuration').value),.01,120,'Export duration'),exportRate=Number($('exportRate').value);validate(state,exportRate);worker=new Worker(new URL('./export-worker.js',import.meta.url),{type:'module'});$('exportWav').disabled=true;$('cancelExport').disabled=false;$('exportProgress').value=0;$('exportStatus').textContent='Rendering…';worker.onmessage=e=>{if(e.data.error){error(Error(e.data.error));$('exportStatus').textContent='Render failed.';endExport();return;}$('exportProgress').value=e.data.progress;$('exportStatus').textContent=`Rendering ${e.data.progress}%`;if(e.data.buffer){download(e.data.buffer,`BrowserToneGen-${exportRate}Hz-${duration}s.wav`,'audio/wav');$('exportStatus').textContent='WAV ready.';message('WAV rendered and downloaded.');log('export',{duration,rate:exportRate});endExport();}};worker.onerror=e=>{error(Error(`Render failed: ${e.message}`));$('exportStatus').textContent='Render failed.';endExport();};worker.postMessage({config:state,rate:exportRate,depth:Number($('exportDepth').value),duration,mono:$('exportChannels').value==='1',normalize:$('normalize').checked});}catch(e){endExport();error(e);}};$('cancelExport').onclick=()=>{endExport();$('exportStatus').textContent='Render cancelled.';};
function diagnostics(){return {version:VERSION,browser:navigator.userAgent,secureContext:globalThis.isSecureContext,...engine.diagnostics(),enabledVoices:state.tones.filter(t=>t.enabled&&!t.muted).length,headroom:state.master.headroom,lastLevels:stats,logs:$('debug').checked?logs:[]};}
$('debug').checked=new URLSearchParams(location.search).get('debug')==='1';$('copyDiagnostics').onclick=async()=>{const s=JSON.stringify(diagnostics(),null,2);$('diagnostics').textContent=s;try{await navigator.clipboard.writeText(s);message('Diagnostics copied.');}catch{message('Select diagnostics text to copy; clipboard unavailable.');}};$('downloadLogs').onclick=()=>download(JSON.stringify(diagnostics(),null,2),'BrowserToneGen-diagnostics.json','application/json');
function grid(canvas){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#24303b';ctx.lineWidth=1;ctx.beginPath();for(let i=1;i<8;i++){ctx.moveTo(i*w/8,0);ctx.lineTo(i*w/8,h);}for(let i=1;i<4;i++){ctx.moveTo(0,i*h/4);ctx.lineTo(w,i*h/4);}ctx.stroke();return ctx;}
function visualize(){requestAnimationFrame(visualize);const now=performance.now();if(now-visualTick<50)return;visualTick=now;renderTransport();if($('debug').checked)$('diagnostics').textContent=JSON.stringify(diagnostics(),null,2);summary();if(!$('visuals').checked)return;if($('freeze').checked)return;
for(const [index,suffix] of [[0,'L'],[1,'R']]){const rms=engine.state==='running'?(stats['rms'+suffix]||0):0,peak=engine.state==='running'?(stats['peak'+suffix]||0):0;$('meter'+suffix).value=peak;$('level'+suffix).textContent=`Peak ${ampToDb(peak).toFixed(1)} · RMS ${ampToDb(rms).toFixed(1)} dBFS`;}
const scope=grid($('scope')),spectrum=grid($('spectrum')),fft=Number($('fft').value),sm=Number($('smoothing').value),ms=Number($('timeScale').value),scale=Number($('amplitudeScale').value);if(!Number.isFinite(ms)||!Number.isFinite(scale)||ms<=0||scale<=0)return;
for(let c=0;c<engine.analysers.length;c++){const a=engine.analysers[c];if(a.fftSize!==fft)a.fftSize=fft;a.smoothingTimeConstant=sm;const data=new Float32Array(fft);a.getFloatTimeDomainData(data);scope.strokeStyle=c?'#e8532a':'#4fb6c4';scope.lineWidth=2;scope.beginPath();const visible=Math.max(2,Math.min(fft,Math.round(rate()*ms/1000)));for(let i=0;i<680;i++){const x=Math.floor(i/680*visible),y=95-data[x]*80*scale;i?scope.lineTo(i,y):scope.moveTo(i,y);}scope.stroke();if(c===0){const freq=new Float32Array(a.frequencyBinCount);a.getFloatFrequencyData(freq);spectrum.strokeStyle='#4fb6c4';spectrum.lineWidth=2;spectrum.beginPath();for(let x=0;x<680;x++){const hz=$('logSpectrum').checked?10*((rate()/2)/10)**(x/679):(rate()/2)*(x/679),bin=Math.min(freq.length-1,Math.floor(hz/rate()*fft)),db=Math.max(-100,freq[bin]);const y=170-(db+100)/100*150;x?spectrum.lineTo(x,y):spectrum.moveTo(x,y);}spectrum.stroke();}}
spectrum.fillStyle='#adb5c0';spectrum.font='12px monospace';spectrum.fillText($('logSpectrum').checked?'10 Hz':'0 Hz',8,185);spectrum.fillText(`${(rate()/2000).toFixed(1)} kHz`,605,185);
}
$('visuals').onchange=()=>{for(const id of ['scope','spectrum'])$(id).hidden=!$('visuals').checked;};
for(const id of ['help','about']){$(id+'Button').onclick=()=>$(id).showModal();document.querySelector(`[data-close="${id}"]`).onclick=()=>$(id).close();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){stop(true);return;}if(e.code==='Space'&&!e.repeat&&!e.altKey&&!e.ctrlKey&&!e.metaKey&&!e.target.closest('input,textarea,select,button,a,[contenteditable=true]')&&!document.querySelector('dialog[open]')){e.preventDefault();engine.state==='stopped'?start():stop();}});
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#config=')){try{load(decodeState(location.hash.slice(8),rate()),'shared configuration');}catch(e){error(e);}}});
window.addEventListener('pagehide',()=>{finishRecording();engine.panic();});window.addEventListener('error',e=>log('uncaught',e.message));window.addEventListener('unhandledrejection',e=>error(e.reason||Error('Unexpected asynchronous error.')));
$('version').textContent=VERSION;$('aboutVersion').textContent=VERSION;render();readSaved();calculate();if(location.hash.startsWith('#config=')){try{state=decodeState(location.hash.slice(8));render();message('Shared configuration loaded. Press Start to play.');}catch(e){error(e);}}visualize();
// Read-only diagnostic surface for browser verification and support.
globalThis.btg={get config(){return structuredClone(state);},get diagnostics(){return diagnostics();}};

function renderAutomation(v){return `<details data-key="${v.id}-auto"><summary>Automation (${v.automation.length} lanes)</summary><p class="hint">Uses the audio clock; included in WAV and presets. Frequency automation sets the pitch before FM/vibrato. Restart playback to audition from time zero.</p>${v.automation.map((a,i)=>`<div data-automation="${i}" class="fields">${select({name:'field',label:'Control'},a.field,Object.keys(AUTOMATABLE))}${select({name:'mode',label:'Curve'},a.mode,['linear','exponential','sine','triangle'])}${field('from','From',a.from,-360,23999)}${field('to','To',a.to,-360,23999)}${field('duration','Seconds / cycle',a.duration,.01,3600)}${field('delay','Delay seconds',a.delay,0,3600)}${check('loop','Loop',a.loop)}<button data-remove-lane="${i}">Remove lane</button></div>`).join('')}<button data-add-lane ${v.automation.length>=7?'disabled':''}>Add automation lane</button></details>`;}
$('tones').addEventListener('change',e=>{const lane=e.target.closest('[data-automation]');if(!lane)return;const next=structuredClone(state),v=next.tones.find(v=>v.id===lane.closest('[data-tone]').dataset.tone),a=v.automation[+lane.dataset.automation],key=e.target.dataset.field;if(!key)return;a[key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.value;if(key==='field'){const [lo,hi]=bounds(a.field,rate(),v);a.from=v[a.field];a.to=hi;a.from=Math.max(lo,Math.min(hi,a.from));}commit(next);});
$('tones').addEventListener('click',e=>{const b=e.target.closest('[data-add-lane],[data-remove-lane]');if(!b)return;const next=structuredClone(state),v=next.tones.find(v=>v.id===b.closest('[data-tone]').dataset.tone);if(b.hasAttribute('data-add-lane')){const key=Object.keys(AUTOMATABLE).find(k=>!v.automation.some(a=>a.field===k));if(!key)return;v.automation.push({field:key,mode:'linear',from:v[key],to:v[key],duration:2,delay:0,loop:false});}else v.automation.splice(+b.dataset.removeLane,1);commit(next);});
let midi=null,learning=false;
function renderMidi(){const selected=$('midiTarget').value;$('midiTarget').innerHTML='<option value="master">Master</option>'+state.tones.map((v,i)=>`<option value="${escape(v.id)}">Tone ${i+1}</option>`).join('');if([...$('midiTarget').options].some(o=>o.value===selected))$('midiTarget').value=selected;renderMidiFields();$('midiMappings').innerHTML=state.midiMappings.map((m,i)=>`<p>Ch ${m.channel} CC ${m.cc} → ${escape(m.target==='master'?'Master':`Tone ${state.tones.findIndex(v=>v.id===m.target)+1}`)} ${escape(m.field)} (${m.min} to ${m.max}) <button data-remove-map="${i}">Remove</button></p>`).join('');}
function renderMidiFields(){const selected=$('midiField').value,keys=$('midiTarget').value==='master'?['gain']:Object.keys(AUTOMATABLE);$('midiField').innerHTML=keys.map(k=>`<option>${k}</option>`).join('');if(keys.includes(selected))$('midiField').value=selected;}
function midiRange(){const target=state.tones.find(v=>v.id===$('midiTarget').value),[lo,hi]=bounds($('midiField').value,rate(),target);$('midiMin').value=lo;$('midiMax').value=hi;}
$('midiTarget').onchange=()=>{renderMidiFields();midiRange();};$('midiField').onchange=midiRange;
$('addMidiMap').onclick=()=>{const next=structuredClone(state);next.midiMappings.push({target:$('midiTarget').value,field:$('midiField').value,channel:Number($('midiChannel').value),cc:Number($('midiCC').value),min:Number($('midiMin').value),max:Number($('midiMax').value)});commit(next);};
$('midiMappings').onclick=e=>{if(!e.target.hasAttribute('data-remove-map'))return;const next=structuredClone(state);next.midiMappings.splice(+e.target.dataset.removeMap,1);commit(next);};
$('midiLearn').onclick=()=>{learning=!learning;$('midiLearn').textContent=learning?'Move a MIDI knob…':'Learn CC';};
function midiMessage(e){const [status,cc,value]=e.data;if((status&0xf0)!==0xb0||value===undefined)return;const channel=(status&15)+1;$('midiStatus').textContent=`Channel ${channel}, CC ${cc}, value ${value}`;if(learning){$('midiChannel').value=channel;$('midiCC').value=cc;learning=false;$('midiLearn').textContent='Learn CC';return;}const next=structuredClone(state);let changed=false;for(const m of next.midiMappings){if(m.cc!==cc||m.channel!==channel)continue;const obj=m.target==='master'?next.master:next.tones.find(v=>v.id===m.target);if(!obj)continue;obj[m.field]=m.min+(m.max-m.min)*value/127;changed=true;}if(changed){if(commit(next,false)){renderGlobals();renderTones();}}}
function attachMidi(){const selected=$('midiInput').value;const inputs=[...midi.inputs.values()].filter(i=>i.state==='connected');$('midiInput').innerHTML='<option value="all">All MIDI inputs</option>'+inputs.map(i=>`<option value="${escape(i.id)}">${escape(i.name||i.id)}</option>`).join('');if(inputs.some(i=>i.id===selected))$('midiInput').value=selected;for(const input of midi.inputs.values())input.onmidimessage=input.state==='connected'&&($('midiInput').value==='all'||input.id===$('midiInput').value)?midiMessage:null;$('midiStatus').textContent=inputs.length?`${inputs.length} MIDI input(s) connected.`:'No MIDI inputs connected.';}
$('connectMidi').onclick=async()=>{try{if(!navigator.requestMIDIAccess)throw Error('Web MIDI is unavailable in this browser. Use Chrome or Edge over HTTPS or localhost.');midi=await navigator.requestMIDIAccess({sysex:false});midi.onstatechange=attachMidi;attachMidi();}catch(e){error(Error(`MIDI: ${e.message}`));}};
$('midiInput').onchange=attachMidi;
$('disconnectMidi').onclick=()=>{if(midi){midi.onstatechange=null;for(const i of midi.inputs.values())i.onmidimessage=null;midi=null;}$('midiStatus').textContent='MIDI disconnected.';};
$('recipeLoad').onclick=()=>{const name=$('recipe').value,s=defaults();s.tones=[tone({frequency:60,duration:4,fadeOut:.2})];const v=s.tones[0];const lane=(field,from,to,duration,mode='exponential',loop=false)=>v.automation.push({field,from,to,duration,mode,loop,delay:0});if(name==='Bass drop')lane('frequency',160,40,3);if(name==='Sweep'){v.duration=10;lane('frequency',40,1000,10);}if(name==='Sub test'){v.duration=15;lane('frequency',20,100,15);}if(name==='Sub drop')lane('frequency',80,25,4);if(name==='Wobble'){v.duration=0;lane('amplitude',.08,.65,.5,'sine',true);}load(s,name);$('exportDuration').value=v.duration||8;};
renderMidi();

function finishRecording(){if(recorder&&recorder.state!=='inactive')recorder.stop();clearTimeout(recordTimer);}
$('recordLive').onclick=async()=>{try{if(recorder)throw Error('A recording is already active.');if(!globalThis.MediaRecorder)throw Error('Live recording is unavailable; use Render WAV to save the automated sound.');if(engine.state==='stopped')await start();if(engine.state==='paused')throw Error('Resume playback before recording.');if(engine.state!=='running')return;const mime=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('No supported live recording format. Use Render WAV.');recordStream=engine.context.createMediaStreamDestination();recordGain=engine.gain;recordGain.connect(recordStream);const chunks=[];recorder=new MediaRecorder(recordStream.stream,{mimeType:mime});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{try{recordGain?.disconnect(recordStream);}catch{}recordStream?.stream.getTracks().forEach(t=>t.stop());download(new Blob(chunks,{type:mime}),`BrowserToneGen-live.${mime.includes('webm')?'webm':mime.includes('ogg')?'ogg':'m4a'}`,mime);recorder=null;recordGain=null;recordStream=null;$('recordLive').disabled=false;$('stopRecord').disabled=true;$('recordStatus').textContent='Recording saved.';};recorder.onerror=e=>{error(Error(e.error?.message||'Recording failed.'));finishRecording();};recorder.start(1000);recordTimer=setTimeout(finishRecording,120000);$('recordLive').disabled=true;$('stopRecord').disabled=false;$('recordStatus').textContent='Recording output, including live MIDI changes. Maximum 120 seconds.';}catch(e){error(e);}};
$('stopRecord').onclick=finishRecording;
