import {validate} from './model.js';
export class Engine {
 constructor(onStats,onError){this.onStats=onStats;this.onError=onError;this.context=null;this.node=null;this.gain=null;this.state='stopped';this.epoch=0;this.analysers=[];this.loaded=false;this.retired=[];}
 async start(config){const epoch=++this.epoch;try{if(!this.context){const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)throw Error('Web Audio is unavailable. Use a current browser.');this.context=new C({latencyHint:'interactive'});}validate(config,this.context.sampleRate);if(!this.context.audioWorklet)throw Error('AudioWorklet is unavailable. Open over HTTPS or localhost. WAV export remains available.');await this.context.resume();if(!this.loaded){await this.context.audioWorklet.addModule(new URL('./worklet.js',import.meta.url));this.loaded=true;}if(epoch!==this.epoch)return;
 this.disconnect();this.node=new AudioWorkletNode(this.context,'btg-tone-engine',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2]});this.gain=this.context.createGain();this.node.connect(this.gain);this.gain.connect(this.context.destination);this.split=this.context.createChannelSplitter(2);this.gain.connect(this.split);this.analysers=[0,1].map(i=>{const a=this.context.createAnalyser();a.fftSize=2048;this.split.connect(a,i);return a;});this.node.port.onmessage=e=>{this.onStats(e.data);if(e.data.done)this.stop(0);};this.node.onprocessorerror=()=>{this.panic();this.onError(Error('Audio processor failed. Press Start to retry.'));};this.node.port.postMessage({type:'config',config});this.state='running';
 }catch(e){if(epoch===this.epoch){this.panic();this.onError(e);}throw e;}}
 update(c){validate(c,this.context?.sampleRate||48000);this.node?.port.postMessage({type:'config',config:c});}
 async pause(){if(this.state==='running'){await this.context.suspend();this.state='paused';}else if(this.state==='paused'){await this.context.resume();this.state='running';}}
 stop(seconds=.03){++this.epoch;if(this.gain&&this.context.state==='running'&&seconds>0){const g=this.gain,node=this.node,split=this.split,analysers=this.analysers;g.gain.cancelScheduledValues(this.context.currentTime);g.gain.setValueAtTime(g.gain.value,this.context.currentTime);g.gain.linearRampToValueAtTime(0,this.context.currentTime+seconds);const retired={node,g,split,analysers};this.retired.push(retired);retired.timeout=setTimeout(()=>{node.disconnect();g.disconnect();split.disconnect();analysers.forEach(a=>a.disconnect());this.retired=this.retired.filter(x=>x!==retired);},seconds*1000+20);this.node=null;this.gain=null;this.split=null;this.analysers=[];}else this.disconnect();this.state='stopped';}
 disconnect(){this.node?.disconnect();this.gain?.disconnect();this.split?.disconnect();for(const a of this.analysers)a.disconnect();this.node=null;this.gain=null;this.split=null;this.analysers=[];}
 panic(){++this.epoch;for(const x of this.retired){clearTimeout(x.timeout);x.g.gain.cancelScheduledValues(this.context.currentTime);x.g.gain.setValueAtTime(0,this.context.currentTime);x.node.disconnect();x.g.disconnect();x.split.disconnect();x.analysers.forEach(a=>a.disconnect());}this.retired=[];if(this.gain){this.gain.gain.cancelScheduledValues(this.context.currentTime);this.gain.gain.setValueAtTime(0,this.context.currentTime);}this.disconnect();this.state='stopped';}
 diagnostics(){return {state:this.state,contextState:this.context?.state||'not created',sampleRate:this.context?.sampleRate||null,baseLatency:this.context?.baseLatency??null,outputLatency:this.context?.outputLatency??null,nodeCount:(this.node?5:0)+this.retired.length*5};}
}
