export const VERSION='0.1.0-beta.1', MAX_TONES=32;
export const WAVES=['sine','square','triangle','sawtooth','reverse saw','pulse','additive','white','pink','brown','blue','violet'];
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const dbToAmp=d=>10**(d/20);
export const ampToDb=a=>a>0?20*Math.log10(a):-80;
export const phaseToRad=p=>p*Math.PI/180;
export const noteToFreq=(n,a=440,c=0)=>a*2**((n-69+c/100)/12);
export const freqToNote=(f,a=440)=>69+12*Math.log2(f/a);
export const cents=(a,b)=>1200*Math.log2(b/a);
export const NOTE_NAMES=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
export function noteLabel(f,a=440){const n=freqToNote(f,a),r=Math.round(n);return `${NOTE_NAMES[((r%12)+12)%12]}${Math.floor(r/12)-1} ${((n-r)*100).toFixed(1)}¢`;}
export function number(v,min,max,name){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error(`${name} must be ${min}–${max}.`);return v;}
function en(v,opts,name){if(!opts.includes(v))throw Error(`Invalid ${name}.`);return v;}
function flag(v,name){if(typeof v!=='boolean')throw Error(`${name} must be true or false.`);return v;}
const integer=(v,a,b,n)=>{number(v,a,b,n);if(!Number.isInteger(v))throw Error(`${n} must be an integer.`);return v;};
let serial=0;
export const tone=(overrides={})=>({id:`t${Date.now().toString(36)}-${++serial}`,enabled:true,muted:false,solo:false,frequency:440,wave:'sine',amplitude:.5,phase:0,pan:0,route:'both',invert:false,delay:0,duration:0,fadeIn:.02,fadeOut:.02,pulseWidth:.5,harmonics:[1,.5,.333,.25,.2,.167,.143,.125],kind:'tone',endFrequency:20000,sweepDuration:10,spacing:'log',direction:'forward',loop:false,repeats:1,steps:8,dwell:.5,transition:.02,mod:'none',modFrequency:5,modDepth:.25,stereoMotion:'none',motionPeriod:2,...overrides});
export function defaults(){return {schemaVersion:1,version:VERSION,master:{gain:-18,muted:false,mono:false,headroom:true,fadeStart:.02,fadeStop:.03},timer:{delay:0,duration:0,repeats:1,rest:1,loop:false},tones:Array.from({length:8},(_,i)=>tone({enabled:i===0,frequency:440*(i+1)})),sequence:[{type:'tone',frequency:1000,endFrequency:2000,duration:2},{type:'silence',frequency:440,endFrequency:2000,duration:1},{type:'sweep',frequency:20,endFrequency:20000,duration:10}],sequenceRepeats:1,sequenceLoop:false};}
export function validate(raw,sampleRate=48000){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Configuration must be an object.');
 let r=raw;if(r.schemaVersion===0){r=structuredClone(r);r.schemaVersion=1;r.tones=r.tones?.map(t=>({...t,amplitude:t.gain??t.amplitude}));}
 if(r.schemaVersion!==1)throw Error('Unsupported preset schema version.');
 const f=(v,n)=>number(v,.1,sampleRate/2-1,n),m=r.master,t=r.timer;
 if(!m||!t||!Array.isArray(r.tones)||r.tones.length>MAX_TONES)throw Error('Missing settings or too many voices.');
 const out={schemaVersion:1,version:VERSION,master:{gain:number(m.gain,-80,0,'Master dB'),muted:flag(m.muted,'Master mute'),mono:flag(m.mono,'Mono'),headroom:flag(m.headroom,'Headroom'),fadeStart:number(m.fadeStart,0,30,'Start fade'),fadeStop:number(m.fadeStop,0,30,'Stop fade')},timer:{delay:number(t.delay,0,3600,'Timer delay'),duration:number(t.duration,0,3600,'Timer duration'),repeats:integer(t.repeats,1,100,'Repetitions'),rest:number(t.rest,0,3600,'Rest'),loop:flag(t.loop,'Timer loop')},tones:[],sequence:[],sequenceRepeats:integer(r.sequenceRepeats,1,100,'Sequence repetitions'),sequenceLoop:flag(r.sequenceLoop,'Sequence loop')};
 const ids=new Set();
 for(const v of r.tones){if(!v||typeof v!=='object')throw Error('Invalid tone.');if(typeof v.id!=='string'||v.id.length>80||ids.has(v.id))throw Error('Invalid or duplicate tone ID.');ids.add(v.id);
 const q={id:v.id};for(const k of ['enabled','muted','solo','invert','loop'])q[k]=flag(v[k],k);
 q.frequency=f(v.frequency,'Frequency');q.endFrequency=f(v.endFrequency,'End frequency');q.wave=en(v.wave,WAVES,'waveform');q.route=en(v.route,['both','left','right'],'route');q.kind=en(v.kind,['tone','sweep','steps','sequence'],'signal type');q.spacing=en(v.spacing,['linear','log'],'spacing');q.direction=en(v.direction,['forward','reverse','pingpong'],'direction');q.mod=en(v.mod,['none','am','fm','tremolo','vibrato','ring'],'modulation');q.stereoMotion=en(v.stereoMotion,['none','alternate','pan'],'stereo motion');
 for(const [k,a,b] of [['amplitude',0,1],['phase',-360,360],['pan',-1,1],['delay',0,3600],['duration',0,3600],['fadeIn',0,30],['fadeOut',0,30],['pulseWidth',.01,.99],['sweepDuration',.01,3600],['dwell',.001,60],['transition',0,1],['modFrequency',.01,1000],['modDepth',0,v.mod==='fm'?20000:v.mod==='vibrato'?2400:1],['motionPeriod',.01,60]])q[k]=number(v[k],a,b,k);
 q.steps=integer(v.steps,2,128,'Steps');q.repeats=integer(v.repeats,1,100,'Repeats');
 if(!Array.isArray(v.harmonics)||v.harmonics.length<1||v.harmonics.length>32)throw Error('Harmonics must contain 1–32 coefficients.');q.harmonics=v.harmonics.map(h=>number(h,-1,1,'Harmonic amplitude'));out.tones.push(q);
 }
 if(!Array.isArray(r.sequence)||r.sequence.length>64)throw Error('Sequence must contain at most 64 stages.');
 for(const s of r.sequence)out.sequence.push({type:en(s.type,['tone','silence','sweep','white','pink','brown'],'stage'),frequency:f(s.frequency,'Stage frequency'),endFrequency:f(s.endFrequency,'Stage end frequency'),duration:number(s.duration,.001,3600,'Stage duration')});
 if(out.tones.some(v=>v.kind==='sequence')&&!out.sequence.length)throw Error('Add a sequence stage first.');return out;
}
export function parsePreset(s,sr=48000){if(s.length>262144)throw Error('Preset file exceeds 256 KB.');return validate(JSON.parse(s),sr);}
export const serialize=s=>JSON.stringify(s,null,2);
export function encodeState(s){const bytes=new TextEncoder().encode(JSON.stringify(s));let text='';for(const b of bytes)text+=String.fromCharCode(b);const code=btoa(text).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');if(code.length>64000)throw Error('Configuration is too large for a share URL.');return code;}
export function decodeState(s,sr=48000){if(s.length>64000)throw Error('Share URL is too large.');const x=atob(s.replaceAll('-','+').replaceAll('_','/'));return parsePreset(new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(x,c=>c.charCodeAt(0))),sr);}
export function harmonicPattern(count,pattern,rolloff=1){return Array.from({length:count},(_,i)=>{const h=i+1;if((['odd','square','triangle'].includes(pattern)&&h%2===0)||(pattern==='even'&&h%2===1))return 0;return (pattern==='triangle'?(-1)**((h-1)/2):1)/h**(pattern==='triangle'?2:rolloff);});}
export function sweepFrequency(v,time){const leg=v.sweepDuration,round=leg*(v.direction==='pingpong'?2:1),total=round*v.repeats;if(!v.loop&&time>=total)return null;let p=(time%round)/leg;if(p>1)p=2-p;if(v.direction==='reverse')p=1-p;return v.spacing==='linear'?v.frequency+(v.endFrequency-v.frequency)*p:v.frequency*(v.endFrequency/v.frequency)**p;}
export function stepFrequency(v,time){const n=v.steps,visits=v.direction==='pingpong'?2*n-2:n,cycle=visits*v.dwell;if(!v.loop&&time>=cycle*v.repeats)return null;const pos=(time%cycle)/v.dwell,idx=Math.floor(pos);const at=i=>{i=(i+visits)%visits;let k=v.direction==='pingpong'?(i<n?i:2*n-2-i):v.direction==='reverse'?n-1-i:i;const p=k/(n-1);return v.spacing==='log'?v.frequency*(v.endFrequency/v.frequency)**p:v.frequency+(v.endFrequency-v.frequency)*p;};const cur=at(idx),next=at(idx+1),frac=pos-idx;if(!v.transition||frac<1-v.transition)return cur;return cur+(next-cur)*(frac-(1-v.transition))/v.transition;}
export function sequenceStage(s,time){const length=s.sequence.reduce((a,b)=>a+b.duration,0);if(!length||(!s.sequenceLoop&&time>=length*s.sequenceRepeats))return null;let t=time%length;for(const stage of s.sequence){if(t<stage.duration)return {...stage,time:t};t-=stage.duration;}return null;}
export function routing(p,route){if(route==='left')return [1,0];if(route==='right')return [0,1];return [Math.cos((p+1)*Math.PI/4),Math.sin((p+1)*Math.PI/4)];}
export function group(mode,f,count,spread){switch(mode){case 'harmonics':return Array.from({length:count},(_,i)=>f*(i+1));case 'subharmonics':return Array.from({length:count},(_,i)=>f/(i+1));case 'major':return [0,4,7].map(n=>f*2**(n/12));case 'minor':return [0,3,7].map(n=>f*2**(n/12));case 'interval':return [f,f*2**(spread/12)];case 'temperament':return Array.from({length:count},(_,i)=>f*2**(i/12));case 'binaural':case 'monaural':return [f,f+spread];default:return Array.from({length:count},(_,i)=>f+(count===1?0:spread*(i/(count-1)-.5)));}}
export function preset(name){const s=defaults();s.tones=[];const add=o=>s.tones.push(tone(o));switch(name){case '20 Hz–20 kHz sweep':add({kind:'sweep',frequency:20,endFrequency:20000});break;case 'Subwoofer sweep':add({kind:'sweep',frequency:20,endFrequency:150});break;case 'Speaker test':add({wave:'pink'});break;case 'Tweeter test':add({frequency:10000});break;case 'Pink noise':add({wave:'pink'});break;case 'White noise':add({wave:'white'});break;case 'Octave stack':[110,220,440,880].forEach(f=>add({frequency:f}));break;case 'Harmonic series':[100,200,300,400,500,600,700,800].forEach(f=>add({frequency:f}));break;case 'Binaural 6 Hz':add({frequency:200,route:'left'});add({frequency:206,route:'right'});break;case 'Monaural beat':case 'Detune beat':add({frequency:440});add({frequency:442});break;case 'Left/right alternate':add({frequency:1000,stereoMotion:'alternate'});break;case 'Left only':add({route:'left'});break;case 'Right only':add({route:'right'});break;case 'Center':add({pan:0});break;case 'Polarity test':add({frequency:1000,route:'left'});add({frequency:1000,route:'right',invert:true});break;case 'Phase 90°':add({route:'left'});add({route:'right',phase:90});break;case 'Pan sweep':add({stereoMotion:'pan',motionPeriod:4});break;case 'Independent L/R':add({frequency:440,route:'left'});add({frequency:880,route:'right'});break;case 'CCIF 19/20 kHz':add({frequency:19000});add({frequency:20000});break;default:add({frequency:parseFloat(name)||440});}return s;}
export const PRESETS=['100 Hz','440 Hz','1 kHz reference','10 kHz','20 Hz–20 kHz sweep','Subwoofer sweep','Speaker test','Tweeter test','Pink noise','White noise','Octave stack','Harmonic series','Binaural 6 Hz','Monaural beat','Detune beat','Left/right alternate','Left only','Right only','Center','Polarity test','Phase 90°','Pan sweep','Independent L/R','CCIF 19/20 kHz'];
// Display names are human-readable; these two require explicit Hz conversion.
export function builtin(name){const s=preset(name);if(name==='1 kHz reference')s.tones[0].frequency=1000;if(name==='10 kHz')s.tones[0].frequency=10000;return s;}
